language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install

script:
  - vendor/bin/simple-phpunit

jobs:
  include:
    - stage: test
      php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
    - stage: release
      if: branch = master
      php: 5.3
      dist: precise
      script:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin

        - curl -LSs https://box-project.github.io/box2/installer.php | php

        - mkdir -p build/
        - php box.phar build

        - aws s3 cp build/insight.phar s3://get.insight.sensiolabs.com/insight.phar --acl=public-read
